blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/retro
    about: The Discord for Retro Dev
  - name: Roblox Group
    url: https://www.roblox.com/games/5846386835/RetroStudio
    about: The Roblox group for Retro Dev
